local-npm: # local-npm 的启动配置
  port: 5080
  pouchPort: 6789
  remote: https://registry.npmjs.org
  remoteSkim: https://replicate.npmjs.com
  url: http://127.0.0.1:5080
  directory: ./data

app:
  port: 2222